server:
  port: 9080 #指定启动端口
  
spring:
 application:
   name: springboot-demo
 profiles:
   active: dev #默认环境
   
 datasource: #数据库配置
   type: com.alibaba.druid.pool.DruidDataSource #这里是配置druid连接池，以下都是druid的配置信息
   url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
   driver-class-name: com.mysql.jdbc.Driver
   username: root
   password: